const cartItems = [
  {
    id: 'recB6qcHPxb62YJ75',
    title: 'Wish',
    singer: '오월오일 ( 五月五日 )',
    price: '25000',
    img: 'https://image.bugsm.co.kr/album/images/original/205513/20551382.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recdRxBsE14Rr2VuJ',
    title: '내 탓이지 뭐',
    singer: '죠지',
    price: '18000',
    img: 'https://image.bugsm.co.kr/album/images/original/41049/4104901.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recwTo120XST3PIoW',
    title: 'Jesus lived in a motel room',
    singer: '혁오 (HYUKOH)',
    price: '28000',
    img: 'https://image.bugsm.co.kr/album/images/original/200944/20094414.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'rec1JZlfCIBOPdcT2',
    title: '숱한 밤들',
    singer: '술탄 오브 더 디스코',
    price: '20000',
    img: 'https://image.bugsm.co.kr/album/images/original/2235/223511.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recwTo160XST3PIoW',
    title: 'After The Love Has Gone',
    singer: 'Earth, Wind & Fire',
    price: '30000',
    img: 'https://image.bugsm.co.kr/album/images/original/80204/8020422.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recaBo120XST3PIoW',
    title: 'Jesus of Suburia',
    singer: 'Green Day',
    price: '12000',
    img: 'https://image.bugsm.co.kr/album/images/original/5522/552236.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recqBo123XST3PIoK',
    title: 'Blanc (feat. George)',
    singer: 'ADOY',
    price: '32000',
    img: 'https://image.bugsm.co.kr/album/images/original/7520/752092.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recqBo133XST3PIoK',
    title: '재',
    singer: '한로로',
    price: '22000',
    img: 'https://image.bugsm.co.kr/album/images/original/206447/20644751.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recqBo145XST3PIoK',
    title: '폭죽과 풍선들',
    singer: '검정치마',
    price: '20000',
    img: 'https://image.bugsm.co.kr/album/images/original/201002/20100228.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'recqBo129XST3PIoK',
    title: 'I Love u..r shoes',
    singer: 'jisokuryClub',
    price: '25000',
    img: 'https://image.bugsm.co.kr/album/images/original/205748/20574811.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'rdaqBo129XST3PIoK',
    title: 'annie',
    singer: 'wave to earth',
    price: '23000',
    img: 'https://image.bugsm.co.kr/album/images/original/41067/4106740.jpg?version=undefined',
    amount: 1,
  },
  {
    id: 'rdaqBo149XQT3PIoK',
    title: 'City Seoul',
    singer: '윤지영',
    price: '21000',
    img: 'https://image.bugsm.co.kr/album/images/original/40857/4085751.jpg?version=undefined',
    amount: 1,
  },
];

export default cartItems;